site_name: FlatImage Documentation
nav:
  - Home: index.md
  - Comparison:
    - comparison.md
  - Commands:
    - fim-root: cmd/root.md
    - fim-exec: cmd/exec.md
    - fim-env: cmd/environment.md
    - fim-desktop: cmd/desktop.md
    - fim-commit: cmd/commit.md
    - fim-layer: cmd/layer.md
    - fim-bind: cmd/bind.md
  - Portal:
    - portal.md
theme: readthedocs
